### ISSUE TITLE
Create unit test for state classes

### ISSUE THREAD

**Issue by Erwan-BR** [Erwan-BR/PLT#7]
# Unit tests

## Purpose
For the rest of the project, we'll need to run **unit tests** using the _Boost library_.

To do this, we'll need to create unit test files in the next deliverable. These tests will enable us to check that constructors work, and that methods are correctly implemented.

## Tasks

- [x] Create Unit Test for the Game class (@AMillasseau)
- [x] Create Unit Test for the Player class (@Hakamatsu)
- [x] Create Unit Test for the Card class (@Xblaze37)
- [x] Create Unit Test for the DevelopmentCard class (@Erwan-BR)
- [x] Create Unit Test for the EmpireCard class (@Hakamatsu)

## Coding rules

- Each pointer must be built with the new keyword and manually destroyed with the delete keyword.
- For each method tested, a clear and precise comment must specify what the test is testing.
- For each class, 100% code-coverage must be guaranteed.
