### ISSUE TITLE
Delete all textures from state, Use constructor from JSON.

### ISSUE THREAD

**Issue by Erwan-BR** [Erwan-BR/PLT#74]
## Description
Textures should be deleted from state and retrieved inside the render.

## To-Do

- [x] Change CreateAllCards to delete usage of texture.
- [x] Delete all constructors that uses textures in state.
- [x] Delete UT that uses design.
- [x] Delete profile picture of player.
- [x] Change in the render the profile picture of player to put EmpireCard->design instead.
- [x] Change CreateAllCards to use instead constructor from JSON of cards.
- [x] Add (in render) a null pointer to texture if the path is incorrect. It will be usefull to avoid 'file not found' in UT.
