### ISSUE TITLE
Create empty method for each classes

### ISSUE THREAD

**Issue by Erwan-BR** [Erwan-BR/PLT#8]
# Empty methods

## Purpose

In order to develop the various methods of our classes, we're now going to create the empty code for each function. What they do will be implemented later.

## Tasks

- [x] Create empty method for the Game class (@AMillasseau)
- [x] Create empty method for the Player class (@Hakamatsu)
- [x] Create empty method for the Card class (@Xblaze37)
- [x] Create empty method for the DevelopmentCard class (@Erwan-BR)
- [x] Create empty method for the EmpireCard class

## Coding rules

In order to produce **clean code** that's the same from one file to the next, here are the coding rules we're going to impose:
- Between each method, skip a line for readability
- Insert "documentation" in the form of a comment. In Visual Studio, all you have to do is type three "/" characters before it automatically completes the comment to be written. See the example files to see how to write comments properly.
- Although the 'this' is optional, you'll need to use it every time to ensure the code is readable.
- The file must end with a non-empty line [C++ standard (N3797)].

**⚠️Warning:** if the coding rules are not respected, the merge in develop will not be accepted and a modification request will be made.

[example_CodingRulesClasses.zip](https://github.com/Erwan-BR/PLT/files/12928301/example_CodingRulesClasses.zip)
